name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Start the server in the background
      - name: Start Server
        run: npm start &

      # Run Cypress tests
      - name: Run Cypress Tests
        run: npx cypress run

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}